-- Run this file in Supabase Dashboard > SQL Editor.
create table if not exists public.dictionary_words (
  id bigint generated by default as identity primary key,
  word text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.recordings (
  id uuid primary key,
  template text not null,
  duration integer not null default 0,
  size integer not null default 0,
  mime_type text not null,
  storage_path text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.practice_sessions (
  id uuid primary key,
  template text not null,
  phrase text not null,
  transcript text not null,
  accuracy integer not null check (accuracy between 0 and 100),
  created_at timestamptz not null default now()
);
insert into public.dictionary_words (word) values ('appointment'), ('conversation'), ('confidence') on conflict (word) do nothing;
insert into storage.buckets (id, name, public) values ('voice-recordings', 'voice-recordings', false) on conflict (id) do nothing;
-- The API uses the server-only service role key, so bucket access stays private.
